name: Control Table Data Ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  control-table-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Pull down this repo
        uses: actions/checkout@v2
      - name: Cache inspec
        uses: actions/cache@v2
        env:
          cache-name: cache-inspec
        with:
          path: |
            /opt/inspec
            /usr/bin/inspec
          key: ${{ env.cache-name }}-4.18.108
      - name: Cache node
        uses: actions/cache@v2
        env:
          cache-name: cache-node
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Install dependencies
        run: |
          command -v inspec >/dev/null 2>&1 || curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.108
          npm install --only=dev
      - name: Ingest and process data
        run: |
          node ./control_table_data_ingest/ingest.js
          jq '.' ./src/assets/data/baselines.json > ./control_table_data_ingest/tmp_baselines.json && mv ./control_table_data_ingest/tmp_baselines.json ./src/assets/data/baselines.json
          jq '.' ./src/assets/data/mitre-saf-control-mapping.json > ./control_table_data_ingest/tmp_mitre-saf-control-mapping.json && mv ./control_table_data_ingest/tmp_mitre-saf-control-mapping.json ./src/assets/data/mitre-saf-control-mapping.json
          find control_table_data_ingest/profiles/ -name \*.json | xargs -I{} sh -c 'jq "." "$1" > ./control_table_data_ingest/tmp.json && mv ./control_table_data_ingest/tmp.json "$1"' sh {}
      - name: Commit processed data
        run: |
          git config --global user.name 'MITRE SAF'
          git config --global user.email 'saf@groups.mitre.org'
          git add ./control_table_data_ingest/profiles
          git add ./src/assets/data/baselines.json
          git add ./src/assets/data/mitre-saf-control-mapping.json
          git commit -m 'Automated ingestion of profiles'
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
