name: Control Table Data Ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  control-table-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Pull down this repo
        uses: actions/checkout@v2
      - name: Cache inspec
        uses: actions/cache@v2
        env:
          cache-name: cache-inspec
        with:
          path: |
            /opt/inspec
          key: ${{ env.cache-name }}-4.18.108
      - name: Cache node
        uses: actions/cache@v2
        env:
          cache-name: cache-node
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Install dependencies
        run: |
          [ -f /opt/inspec/bin/inspec ] && sudo ln -s /opt/inspec/bin/inspec /usr/bin/inspec || curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.108
          export INSPECJS_VER=`node -p -e "require('./package-lock.json').dependencies.inspecjs.version"`
          export CSVPARSE_VER=`node -p -e "require('./package-lock.json').dependencies['csv-parse'].version"`
          npm install --no-save --no-package-lock inspecjs@"$INSPECJS_VER" csv-parse@"$CSVPARSE_VER"
      - name: Ingest and process data
        run: |
          node ./control_table_data_ingest/ingest.js
      - name: Commit processed data
        run: |
          git config --global user.name 'MITRE SAF'
          git config --global user.email 'saf@groups.mitre.org'
          git add ./control_table_data_ingest/profiles
          git add ./src/assets/data/baselines.json
          git add ./src/assets/data/mitre-saf-control-mapping.json
          git commit -m 'Automated ingestion of profiles' || true
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
