name: Control Table Data Ingestion

on:
  # swap to schedule later on
  workflow_dispatch:

jobs:
  control-table-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
      - uses: actions/checkout@v2
      - name: Ingest data
        run: node ./control_table_data_ingest/ingest.js
      - name: Commit processed data
        # modify the git config stuff to be some 'official' saf account
        # modify to not add all, just the generated file (currently will add on a lot of temporary directories)
        run: |
          git config --global user.name 'Amndeep Singh Mann'
          git config --global user.email 'amann@mitre.org'
          git commit -am 'Automated ingestion of profiles'
          git push
